### ISSUE TITLE
fatal: Repository 'https://github.com/MaikuB/hnpwa_client.git/' not found

### ISSUE THREAD

**Issue by mars3142** [MaikuB/supnews#3]
I can't call **flutter packages get**, because of missing dependency.

**Comment by BharatsDruv** [comment]
'MaikuB' has removed this repository.

**Comment by MaikuB** [comment]
Sorry only just saw this message as I didn't have it configured to watch the repo... Yes I did remove the repo as the bug fix I submitted got merged to the package itself so you should be about to reference it from pub directly. I'll see about updating this repo
